config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :new, :create]
  resources :purchases, only: [:index, :new, :create]

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/discount.rb
class Discount < ApplicationRecord
  enum boundary: [:equal, :less_than, :greater_than]
  enum condition_type: [:quantity, :money_spent]
  enum discount_type: [:percentage, :money]

  validates :boundary, presence: true
  validates :condition_type, presence: true
  validates :condition_amount, presence: true
  validates :discount_type, presence: true
  validates :discount_amount, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :price, presence: true

  has_many :discounts

  accepts_nested_attributes_for :discounts
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @product.discounts.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, discounts_attributes:
      [:boundary, :condition_type, :condition_amount, :discount_type, :discount_amount])
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases = Purchase.all
  end

  def new
    @products = Product.all
    @purchase = Purchase.new
  end

  def create
    @purchase = Purchase.new
    @purchase.price = PurchaseCalculator.new(params[:products_quantity]).calculate_price
    @purchase.save
    redirect_to purchases_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_errors_helper.rb
module FormErrorsHelper
  def format_errors(object)
    messages = []
    object.errors.messages.each do |key, errors|
      errors.each{ |e| messages << "#{ key.to_s.humanize } #{ e }" }
    end
    messages
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Local Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.css',
      'application',
      media: 'all',
      'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background-primary">
    <div class="container content">
      <div class="row">
        <%= link_to "Products", products_path %>
        ::
        <%= link_to "Purchases", purchases_path %>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/products/index.html.erb
<h3>Products(<%= link_to "+", new_product_path %>)</h3>

<% @products.each do |product| %>
  <ul>
    <li><b><%= product.name %></b></li>
    <li>Price: <%= product.price %></li>
    <li>Discounts</li>
    <% product.discounts.each do |discount| %>
      <li>
        <%=
          "IF #{ discount.condition_type } IS #{ discount.boundary } \
          #{ discount.condition_amount } THEN GOT #{ discount.discount_amount } \
          #{ discount.discount_type } OF DISCOUNT"
        %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/products/new.html.erb
<div class="content background-content ">
  <div class="row">
    <h3>New Product</h3>

    <ul>
      <% format_errors(@product).each do |m| %>
        <li class="message error"><%= m %></li>
      <% end %>
    </ul>

    <%= form_for @product, url: products_path(@product) do |f| %>
      <label>Name</label>
      <%= f.text_field :name %>

      <label>Price</label>
      <%= f.text_field :price, placeholder: "U$ 9.99" %>

      <label>Discounts</label>
      <%= f.fields_for :discounts do |df| %>
        <div class="row">
          IF
          <%=
            df.select :condition_type, options_for_select({
              "quantity": :quantity, "money_spent": :money_spent
            })
          %>
          IS
          <%=
            df.select :boundary, options_for_select({
              "equal": :equal, "less than": :less_than, "greater than": :greater_than
            })
          %>
          <%= df.text_field :condition_amount %>
          GIVES
          <%= df.text_field :discount_amount %>
          <%= df.select :discount_type, options_for_select({ "%": :percentage, "$": :money}) %>
          OF DISCOUNT
        </div>
      <% end %>

      <div class="row">
        <%= f.submit "Register", class: "button-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/purchases/index.html.erb
<div class="row">
  <h3>Purchases(<%= link_to "+", new_purchase_path %>)</h3>

  <% @purchases.each_with_index do |purchase, i| %>
    <ul>
      <li><b>Purchase <%= i + 1 %>: <%= number_to_currency purchase.price %></b></li>
    </ul>
  <% end %>
</div>

app/views/purchases/new.html.erb
<div class="content background-content ">
  <div class="row">
    <h3>New Purchase</h3>

    <ul>
      <% format_errors(@purchase).each do |m| %>
        <li class="message error"><%= m %></li>
      <% end %>
    </ul>

    <%= form_for @purchase, url: purchases_path(@purchase) do |f| %>
      <% @products.each do |product| %>
        <div class="row">
          <%= number_field_tag "products_quantity[#{ product.id }]", 0 %>
          <%= "#{ product.name }: #{ number_to_currency product.price }" %>
        </div>
      <% end %>

      <div class="row">
        <%= f.submit "Buy", class: "button-primary" %>
      </div>
    <% end %>
  </div>
</div>